In [32]:
N= 6
if N%3 != 0:
    raise Exception("size of Network is not exactly divisible by 3")

# np.random.seed(92)
n = N/3
FAST = 0.7
MEDIUM = 0.3
SLOW = 0.0

a =  ( np.random.rand(n,n) - 0.5  ) * 2
b =  ( np.random.rand(n,n) - 0.5  ) * 1
c =  ( np.random.rand(n,n) - 0.5  ) * 0.5


d = ( np.random.rand(n,n) - 0.5 ) * 2 * 0.1
e = ( np.random.rand(n,n) - 0.5 ) * 2 * 0.1
f = ( np.random.rand(n,n) - 0.5 ) * 2 * 0.1
g = ( np.random.rand(n,n) - 0.5 ) * 2 * 0.1

h = np.zeros((n,n))
print np.matrix( np.ma.concatenate( [ np.ma.concatenate([a,d,h]), np.ma.concatenate([g,b,e]), np.ma.concatenate([h,f,c]) ], axis = 1) )



[[ 0.7622877   0.68130173  0.05068213  0.09392972  0.          0.        ]
 [-0.15013443 -0.97326656 -0.0198273   0.06725969  0.          0.        ]
 [-0.04543618 -0.07258727 -0.32436559  0.24920164  0.07030756 -0.04573819]
 [-0.02089495 -0.06469026 -0.11783667 -0.34991942  0.02985892  0.05590905]
 [ 0.          0.         -0.04818729  0.06175382  0.14160977 -0.2219946 ]
 [ 0.          0.          0.04586628  0.01747131  0.03249752  0.22760184]]


In [7]:
np.random.rand(10,10)


array([[0.82603112, 0.59328145, 0.77315575, 0.44588414, 0.45110399,
        0.46933108, 0.1846077 , 0.0116822 , 0.95694534, 0.94292293],
       [0.04774351, 0.94334876, 0.53635171, 0.18752163, 0.27960891,
        0.57508552, 0.47803854, 0.88593103, 0.23171935, 0.98905735],
       [0.60342469, 0.88643691, 0.45243689, 0.69296928, 0.94589352,
        0.29285374, 0.64731188, 0.1854676 , 0.38483391, 0.02409181],
       [0.55547818, 0.79527145, 0.47844406, 0.03193153, 0.03557628,
        0.98502256, 0.70410561, 0.87443481, 0.10537433, 0.51951306],
       [0.27890975, 0.07442907, 0.48490038, 0.92110076, 0.57424435,
        0.00852029, 0.90408875, 0.23660351, 0.1669236 , 0.89202183],
       [0.34276831, 0.72298435, 0.36724532, 0.95324483, 0.18458433,
        0.11837575, 0.6427026 , 0.69412912, 0.93790577, 0.23196627],
       [0.01343691, 0.76462622, 0.62399015, 0.31490392, 0.36314095,
        0.41534039, 0.47742071, 0.82198152, 0.18732559, 0.05212625],
       [0.77807278, 0.00756046, 0.5673430